name: davidcoats
favicon: null
layout_spectrum: 0.9790953726042062
typography_spectrum: 0.8566009127534926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8864275333471596
  lightness: 0.6740767369046807
  saturation: 0.5696645230054855
  rhythmicContrast: 0.5188332239631563
purpose: []
